package Presentacio;

/**
 * @autor Victor
 * @dataCreación 18/11/2014
 * @dataÚltimaModificación 19/12/2014
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private CtrlPresentacio cPres;
    
    /**
     * Creates new form VistaPrincipalJFrame
     */
    public VistaPrincipal() {
        initComponents();
    }
    
    /**
     * Creates new form VistaPrincipalJFrame
     */
    public VistaPrincipal(CtrlPresentacio cpres) {
        this.cPres = cpres;
        initComponents();
        this.setResizable(false);
        vistaInicio.setVisible(true);
        vistaGestionMapas.setVisible(false);
        vistaGestionReuniones.setVisible(false);
        vistaSimulacion.setVisible(false);
        vistaResultados.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butonPanel = new javax.swing.JPanel();
        titSmiley = new javax.swing.JLabel();
        mapsButton = new javax.swing.JButton();
        reunionButton = new javax.swing.JButton();
        simularButton = new javax.swing.JButton();
        resultadosButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        vistaInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vistaGestionMapas = new Presentacio.VistaGestionMapas(this.cPres);
        vistaGestionReuniones = new Presentacio.VistaGestionReuniones(this.cPres);
        vistaSimulacion = new Presentacio.VistaSimulacion(this.cPres);
        vistaResultados = new Presentacio.VistaResultados(this.cPres);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smiley");

        butonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titSmiley.setFont(new java.awt.Font("Optima", 1, 36)); // NOI18N
        titSmiley.setText("Smiley");

        mapsButton.setText("Gestionar Mapas");
        mapsButton.setPreferredSize(new java.awt.Dimension(157, 29));
        mapsButton.setRequestFocusEnabled(false);
        mapsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapsButtonActionPerformed(evt);
            }
        });

        reunionButton.setText("Gestionar Reuniones");
        reunionButton.setPreferredSize(new java.awt.Dimension(157, 29));
        reunionButton.setRequestFocusEnabled(false);
        reunionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reunionButtonActionPerformed(evt);
            }
        });

        simularButton.setText("Simular Reunión");
        simularButton.setPreferredSize(new java.awt.Dimension(157, 29));
        simularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simularButtonActionPerformed(evt);
            }
        });

        resultadosButton.setText("Ver Resultados");
        resultadosButton.setToolTipText("");
        resultadosButton.setPreferredSize(new java.awt.Dimension(157, 29));
        resultadosButton.setRequestFocusEnabled(false);
        resultadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadosButtonActionPerformed(evt);
            }
        });

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout butonPanelLayout = new javax.swing.GroupLayout(butonPanel);
        butonPanel.setLayout(butonPanelLayout);
        butonPanelLayout.setHorizontalGroup(
            butonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(butonPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titSmiley)
                .addGap(28, 28, 28)
                .addComponent(mapsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(reunionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simularButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(resultadosButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        butonPanelLayout.setVerticalGroup(
            butonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(butonPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(butonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadosButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirButton)
                    .addComponent(simularButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reunionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mapsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
            .addComponent(titSmiley, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        getContentPane().add(butonPanel, java.awt.BorderLayout.NORTH);

        displayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        displayPanel.setLayout(new javax.swing.OverlayLayout(displayPanel));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacio/resources/soldados.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setAutoscrolls(true);
        jLabel1.setMaximumSize(new java.awt.Dimension(877, 546));
        jLabel1.setMinimumSize(new java.awt.Dimension(877, 546));
        jLabel1.setPreferredSize(new java.awt.Dimension(877, 546));

        javax.swing.GroupLayout vistaInicioLayout = new javax.swing.GroupLayout(vistaInicio);
        vistaInicio.setLayout(vistaInicioLayout);
        vistaInicioLayout.setHorizontalGroup(
            vistaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
        );
        vistaInicioLayout.setVerticalGroup(
            vistaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );

        displayPanel.add(vistaInicio);
        displayPanel.add(vistaGestionMapas);
        displayPanel.add(vistaGestionReuniones);
        displayPanel.add(vistaSimulacion);
        displayPanel.add(vistaResultados);

        getContentPane().add(displayPanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(958, 652));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mapsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapsButtonActionPerformed
        vistaInicio.setVisible(false);
        vistaGestionMapas.setVisible(true);
        vistaGestionReuniones.setVisible(false);
        vistaSimulacion.setVisible(false);
        vistaResultados.setVisible(false);
    }//GEN-LAST:event_mapsButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirButtonActionPerformed

    private void reunionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reunionButtonActionPerformed
        vistaInicio.setVisible(false);
        vistaGestionMapas.setVisible(false);
        vistaGestionReuniones.setVisible(true);
        vistaSimulacion.setVisible(false);
        vistaResultados.setVisible(false);
        vistaGestionReuniones.mostrarReunion();
    }//GEN-LAST:event_reunionButtonActionPerformed

    private void simularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simularButtonActionPerformed
        vistaInicio.setVisible(false);
        vistaGestionMapas.setVisible(false);
        vistaGestionReuniones.setVisible(false);
        vistaSimulacion.setVisible(true);
        vistaResultados.setVisible(false);
        vistaSimulacion.esconderNoSolucionPanel();
    }//GEN-LAST:event_simularButtonActionPerformed

    private void resultadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadosButtonActionPerformed
        vistaInicio.setVisible(false);
        vistaGestionMapas.setVisible(false);
        vistaGestionReuniones.setVisible(false);
        vistaSimulacion.setVisible(false);
        vistaResultados.setVisible(true);
        vistaResultados.mostrarResultados();
    }//GEN-LAST:event_resultadosButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel butonPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mapsButton;
    private javax.swing.JButton resultadosButton;
    private javax.swing.JButton reunionButton;
    private javax.swing.JButton salirButton;
    private javax.swing.JButton simularButton;
    private javax.swing.JLabel titSmiley;
    private Presentacio.VistaGestionMapas vistaGestionMapas;
    private Presentacio.VistaGestionReuniones vistaGestionReuniones;
    private javax.swing.JPanel vistaInicio;
    private Presentacio.VistaResultados vistaResultados;
    private Presentacio.VistaSimulacion vistaSimulacion;
    // End of variables declaration//GEN-END:variables

    public void cierraCrearMapaAbreVistaMapa() {
        this.vistaGestionMapas.cierraCrearMapaAbreVistaMapa();
    }

    void eliminaResultados() {
        vistaResultados.eliminaResultados();
    }

    void borrarParamsReunion() {
        vistaGestionReuniones.borrarParamsReunion();
        vistaResultados.borrarTituloReunion();
    }

}
