package Presentacio;

import java.util.Vector;

/**
 * @autor Flor
 * @dataCreación 28/11/2014
 * @dataÚltimaModificación 30/11/2014
 */
public class VistaVerMapa extends javax.swing.JPanel {

    private CtrlPresentacio cPres;
    
    /**
     * Creates new form VistaMapaNuevo
     */
    public VistaVerMapa() {
        initComponents();
    }
    
    /**
     * Creates new form VistaMapaNuevo
     */
    public VistaVerMapa(CtrlPresentacio cpres) {
        this.cPres = cpres;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();
        nombreMapa = new javax.swing.JLabel();
        verticesLabel = new javax.swing.JLabel();
        aristasLabel = new javax.swing.JLabel();
        scrollVertices = new javax.swing.JScrollPane();
        conjuntoVertices = new javax.swing.JTextArea();
        scrollAristas = new javax.swing.JScrollPane();
        conjuntoAristas = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        titulo.setText("Mapa cargado en el sistema actualmente");
        titlePanel.add(titulo);

        add(titlePanel, java.awt.BorderLayout.PAGE_START);

        nombreMapa.setText("No hay ningún mapa cargado en el sistema");

        verticesLabel.setText("Vértices (id:nombre):");

        aristasLabel.setText("Aristas (id:nombre:id pueblo origen:id pueblo destino:capacidad:flow:peso):");

        conjuntoVertices.setColumns(20);
        conjuntoVertices.setRows(5);
        conjuntoVertices.setRequestFocusEnabled(false);
        scrollVertices.setViewportView(conjuntoVertices);

        conjuntoAristas.setColumns(20);
        conjuntoAristas.setRows(5);
        conjuntoAristas.setRequestFocusEnabled(false);
        scrollAristas.setViewportView(conjuntoAristas);

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollVertices)
                    .addComponent(scrollAristas)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, displayPanelLayout.createSequentialGroup()
                        .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreMapa)
                            .addComponent(verticesLabel)
                            .addComponent(aristasLabel))
                        .addGap(0, 189, Short.MAX_VALUE)))
                .addContainerGap())
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(nombreMapa)
                .addGap(34, 34, 34)
                .addComponent(verticesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollVertices, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(aristasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollAristas, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(displayPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aristasLabel;
    private javax.swing.JTextArea conjuntoAristas;
    private javax.swing.JTextArea conjuntoVertices;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel nombreMapa;
    private javax.swing.JScrollPane scrollAristas;
    private javax.swing.JScrollPane scrollVertices;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel verticesLabel;
    // End of variables declaration//GEN-END:variables

    public void mostrarlo(){
        boolean hayMapa = compruebaExisteMapa();
        if (hayMapa){
            String nombre = this.cPres.getNombreMapa();
            nombreMapa.setText("Nombre del mapa: " + nombre);
            
            Vector<String> pueblos = this.cPres.getPueblosMapa();
            Vector<String> tramos = this.cPres.getTramosMapa();
            
            String strPMapa = "";
            for (int i = 0; i < pueblos.size(); i++){
                strPMapa += " ";
                strPMapa += pueblos.get(i);
                strPMapa += "\n";
            }
            System.out.println(strPMapa);
            
            String strTMapa = "";
            for (int i = 0; i < tramos.size(); i++){
                strTMapa += " ";
                strTMapa += tramos.get(i);
                strTMapa += "\n";
            }
            System.out.println(strTMapa);

            conjuntoVertices.setText(strPMapa);
            conjuntoAristas.setText(strTMapa);
        }
    }
    
    private boolean compruebaExisteMapa() {
        return this.cPres.hayMapaCargado();
    }
}
