package Presentacio;

import javax.swing.JOptionPane;

/**
 * @autor Flor
 * @dataCreación 25/11/2014
 * @dataÚltimaModificación 15/12/2014
 */
public class VistaSimulacion extends javax.swing.JPanel {

    private CtrlPresentacio cPres;

    /**
     * Creates new form VistaGestionMapas
     */
    public VistaSimulacion() {
        initComponents();
    }

    /**
     * Creates new form VistaGestionMapas
     */
    public VistaSimulacion(CtrlPresentacio cpres) {
        this.cPres = cpres;
        initComponents();
        fotoPanel.setVisible(true);
        noSolucionPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simularPanel = new javax.swing.JPanel();
        simularButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();
        noSolucionPanel = new javax.swing.JPanel();
        explicacionNoResult = new javax.swing.JLabel();
        queQuiereLabel = new javax.swing.JLabel();
        cambiarDest = new javax.swing.JButton();
        subreunion = new javax.swing.JButton();
        ocultarNoResult = new javax.swing.JButton();
        optionNoSolutionPanel = new javax.swing.JPanel();
        newDestPanel = new javax.swing.JPanel();
        newDestLabel = new javax.swing.JLabel();
        newDestField = new javax.swing.JTextField();
        newDest = new javax.swing.JButton();
        newSubreunionPanel = new javax.swing.JPanel();
        newSubreunion = new javax.swing.JButton();
        newDestSubreunionField = new javax.swing.JTextField();
        newDestSubreunion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fotoPanel = new javax.swing.JPanel();
        fotoLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        simularButton.setText("¡Hacer la simulación!");
        simularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simularButtonActionPerformed(evt);
            }
        });
        simularPanel.add(simularButton);

        resultLabel.setText("result");
        simularPanel.add(resultLabel);

        add(simularPanel, java.awt.BorderLayout.PAGE_START);

        displayPanel.setLayout(new javax.swing.OverlayLayout(displayPanel));

        explicacionNoResult.setText("                La simulación no ha obtendio una ruta para cada agente. Hay algunos que no pueden llegar al pueblo de destino");

        queQuiereLabel.setText("¿Qué desea hacer?");

        cambiarDest.setText("Cambiar la ciudad de destino");
        cambiarDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarDestActionPerformed(evt);
            }
        });

        subreunion.setText("Hacer una subreunión");
        subreunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subreunionActionPerformed(evt);
            }
        });

        ocultarNoResult.setText("Nada");
        ocultarNoResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocultarNoResultActionPerformed(evt);
            }
        });

        optionNoSolutionPanel.setLayout(new javax.swing.OverlayLayout(optionNoSolutionPanel));

        newDestLabel.setText("Nuevo destino:");

        newDestField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDestFieldActionPerformed(evt);
            }
        });

        newDest.setText("Actualizar destino");
        newDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newDestPanelLayout = new javax.swing.GroupLayout(newDestPanel);
        newDestPanel.setLayout(newDestPanelLayout);
        newDestPanelLayout.setHorizontalGroup(
            newDestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newDestPanelLayout.createSequentialGroup()
                .addGroup(newDestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newDestPanelLayout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(newDestLabel))
                    .addGroup(newDestPanelLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addGroup(newDestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newDest, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newDestField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        newDestPanelLayout.setVerticalGroup(
            newDestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newDestPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(newDestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newDestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newDest)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        optionNoSolutionPanel.add(newDestPanel);

        newSubreunion.setText("Actualizar destino");
        newSubreunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSubreunionActionPerformed(evt);
            }
        });

        newDestSubreunionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDestSubreunionFieldActionPerformed(evt);
            }
        });

        newDestSubreunion.setText("Destino alternativo para la subreunión:");

        jLabel1.setText("Los agentes que no hayan podido llegar al destino principal intentaran llegar a este.");

        javax.swing.GroupLayout newSubreunionPanelLayout = new javax.swing.GroupLayout(newSubreunionPanel);
        newSubreunionPanel.setLayout(newSubreunionPanelLayout);
        newSubreunionPanelLayout.setHorizontalGroup(
            newSubreunionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newSubreunionPanelLayout.createSequentialGroup()
                .addGroup(newSubreunionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newSubreunionPanelLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addGroup(newSubreunionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newSubreunion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newDestSubreunionField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(newSubreunionPanelLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(newDestSubreunion))
                    .addGroup(newSubreunionPanelLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        newSubreunionPanelLayout.setVerticalGroup(
            newSubreunionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newSubreunionPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(newDestSubreunion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newDestSubreunionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newSubreunion)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        optionNoSolutionPanel.add(newSubreunionPanel);

        javax.swing.GroupLayout noSolucionPanelLayout = new javax.swing.GroupLayout(noSolucionPanel);
        noSolucionPanel.setLayout(noSolucionPanelLayout);
        noSolucionPanelLayout.setHorizontalGroup(
            noSolucionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noSolucionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cambiarDest, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subreunion, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ocultarNoResult, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(noSolucionPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(explicacionNoResult)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(noSolucionPanelLayout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(queQuiereLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(noSolucionPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(optionNoSolutionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        noSolucionPanelLayout.setVerticalGroup(
            noSolucionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noSolucionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(explicacionNoResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(queQuiereLabel)
                .addGap(18, 18, 18)
                .addGroup(noSolucionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cambiarDest)
                    .addComponent(subreunion)
                    .addComponent(ocultarNoResult))
                .addGap(18, 18, 18)
                .addComponent(optionNoSolutionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        displayPanel.add(noSolucionPanel);

        fotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacio/resources/World-War-Two-Soldiers-Training.jpg"))); // NOI18N
        fotoPanel.add(fotoLabel);

        displayPanel.add(fotoPanel);

        add(displayPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void simularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simularButtonActionPerformed
        boolean hayReunion = this.cPres.hayReunion();
        if (hayReunion) {
            if (!this.cPres.getReunionHecha()) {
                this.cPres.cHacerReunion();
                boolean haySol = this.cPres.haySolucion();
                if (haySol) {
                    resultLabel.setText("Simulación hecha. Ya puedes consultar los resultados");
                    noSolucionPanel.setVisible(false);
                    fotoPanel.setVisible(true);
                    this.cPres.resetMapa();
                } else {
                    resultLabel.setText("Simulación hecha. Sin solución");
                    fotoPanel.setVisible(false);
                    noSolucionPanel.setVisible(true);
                    optionNoSolutionPanel.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "La reunión ya se ha simulado con estos parametros");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No puedes hacer una simulación si no hay una reunión definida");
        }
    }//GEN-LAST:event_simularButtonActionPerformed

    private void subreunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subreunionActionPerformed
        optionNoSolutionPanel.setVisible(true);
        newDestPanel.setVisible(false);
        newSubreunionPanel.setVisible(true);
    }//GEN-LAST:event_subreunionActionPerformed

    private void ocultarNoResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocultarNoResultActionPerformed
        noSolucionPanel.setVisible(false);
        fotoPanel.setVisible(true);
    }//GEN-LAST:event_ocultarNoResultActionPerformed

    private void cambiarDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarDestActionPerformed
        optionNoSolutionPanel.setVisible(true);
        newSubreunionPanel.setVisible(false);
        newDestPanel.setVisible(true);
    }//GEN-LAST:event_cambiarDestActionPerformed

    private void newDestFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDestFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDestFieldActionPerformed

    private void newDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDestActionPerformed
        int numPueblos = this.cPres.getNumPueblos();
        boolean destValido = (isNumeric(newDestField.getText()) && Integer.parseInt(newDestField.getText()) >= 0 && Integer.parseInt(newDestField.getText()) < numPueblos);
        if (destValido) {
            this.cPres.cambiarDestinoReunion(newDestField.getText());
            noSolucionPanel.setVisible(false);
            fotoPanel.setVisible(true);
            resultLabel.setText("");
            JOptionPane.showMessageDialog(null, "Destino cambiado, ya puedes volver a hacer la simulación");
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, introduce un pueblo de destino válido");
        }
    }//GEN-LAST:event_newDestActionPerformed

    private void newSubreunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSubreunionActionPerformed
        String puebloDestino = newDestSubreunionField.getText();
        int numPueblos = this.cPres.getNumPueblos();
        boolean destValido = (isNumeric(puebloDestino) && Integer.parseInt(puebloDestino) >= 0 && Integer.parseInt(puebloDestino) < numPueblos);
        if (destValido) {
            this.cPres.cHacerSubreunion(puebloDestino);
            boolean haySol = this.cPres.haySolucion();
            if (haySol) {
                noSolucionPanel.setVisible(false);
                fotoPanel.setVisible(true);
                resultLabel.setText("Simulación hecha. Ya puedes consultar los resultados");
                this.cPres.resetMapa();
            } else {
                resultLabel.setText("Sigue sin haber solución. Lo sentimos Smiley");
                noSolucionPanel.setVisible(false);
                fotoPanel.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, introduce un pueblo de destino válido");
        }
    }//GEN-LAST:event_newSubreunionActionPerformed

    private void newDestSubreunionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDestSubreunionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDestSubreunionFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarDest;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel explicacionNoResult;
    private javax.swing.JLabel fotoLabel;
    private javax.swing.JPanel fotoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newDest;
    private javax.swing.JTextField newDestField;
    private javax.swing.JLabel newDestLabel;
    private javax.swing.JPanel newDestPanel;
    private javax.swing.JLabel newDestSubreunion;
    private javax.swing.JTextField newDestSubreunionField;
    private javax.swing.JButton newSubreunion;
    private javax.swing.JPanel newSubreunionPanel;
    private javax.swing.JPanel noSolucionPanel;
    private javax.swing.JButton ocultarNoResult;
    private javax.swing.JPanel optionNoSolutionPanel;
    private javax.swing.JLabel queQuiereLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton simularButton;
    private javax.swing.JPanel simularPanel;
    private javax.swing.JButton subreunion;
    // End of variables declaration//GEN-END:variables

    private boolean isNumeric(String str) {
        return (str.matches("[+-]?\\d*(\\.\\d+)?") && str.equals("") == false);
    }

    void esconderNoSolucionPanel() {
        noSolucionPanel.setVisible(false);
        fotoPanel.setVisible(true);
        resultLabel.setText("");
    }
}
