package Presentacio;

/**
 * @autor Flor
 * @dataCreación 20/11/2014
 * @dataÚltimaModificación 13/11/2014
 */
public class VistaGestionMapas extends javax.swing.JPanel {

    private CtrlPresentacio cPres;
    
    /**
     * Creates new form VistaGestionMapas
     */
    public VistaGestionMapas() {
        initComponents();
    }
    
    /**
     * Creates new form VistaGestionMapas
     */
    public VistaGestionMapas(CtrlPresentacio cpres) {
        this.cPres = cpres;
        initComponents();
        opcionesMapaDefault.setVisible(true);
        vistaMapaNuevo.setVisible(false);
        vistaModificarMapa.setVisible(false);
        vistaGuardarMapa.setVisible(false);
        vistaVerMapa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoButton = new javax.swing.JButton();
        modificarButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();
        verButton = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        opcionesMapaDefault = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vistaMapaNuevo = new Presentacio.VistaMapaNuevo(this.cPres);
        vistaModificarMapa = new Presentacio.VistaModificarMapa(this.cPres);
        vistaGuardarMapa = new Presentacio.VistaGuardarMapa(this.cPres);
        vistaVerMapa = new Presentacio.VistaVerMapa(this.cPres);

        setPreferredSize(new java.awt.Dimension(836, 546));

        nuevoButton.setText("Mapa Nuevo");
        nuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoButtonActionPerformed(evt);
            }
        });

        modificarButton.setText("Modificar Mapa");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        guardarButton.setText("Guardar Mapa");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        verButton.setText("Ver Mapa");
        verButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verButtonActionPerformed(evt);
            }
        });

        container.setLayout(new javax.swing.OverlayLayout(container));

        jLabel1.setText("Esta es la gestión de mapas de Smiley");

        javax.swing.GroupLayout opcionesMapaDefaultLayout = new javax.swing.GroupLayout(opcionesMapaDefault);
        opcionesMapaDefault.setLayout(opcionesMapaDefaultLayout);
        opcionesMapaDefaultLayout.setHorizontalGroup(
            opcionesMapaDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMapaDefaultLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        opcionesMapaDefaultLayout.setVerticalGroup(
            opcionesMapaDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMapaDefaultLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel1)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        container.add(opcionesMapaDefault);
        container.add(vistaMapaNuevo);
        container.add(vistaModificarMapa);
        container.add(vistaGuardarMapa);
        container.add(vistaVerMapa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guardarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(nuevoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(nuevoButton)
                .addGap(18, 18, 18)
                .addComponent(modificarButton)
                .addGap(20, 20, 20)
                .addComponent(guardarButton)
                .addGap(18, 18, 18)
                .addComponent(verButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        opcionesMapaDefault.setVisible(false);
        vistaMapaNuevo.setVisible(false);
        vistaModificarMapa.setVisible(false);
        vistaGuardarMapa.setVisible(true);
        vistaVerMapa.setVisible(false);
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void nuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoButtonActionPerformed
        opcionesMapaDefault.setVisible(false);
        vistaMapaNuevo.setVisible(true);
        vistaModificarMapa.setVisible(false);
        vistaGuardarMapa.setVisible(false);
        vistaVerMapa.setVisible(false);
    }//GEN-LAST:event_nuevoButtonActionPerformed

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
        opcionesMapaDefault.setVisible(false);
        vistaMapaNuevo.setVisible(false);
        vistaModificarMapa.setVisible(true);
        vistaGuardarMapa.setVisible(false);
        vistaVerMapa.setVisible(false);
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void verButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verButtonActionPerformed
        opcionesMapaDefault.setVisible(false);
        vistaMapaNuevo.setVisible(false);
        vistaModificarMapa.setVisible(false);
        vistaGuardarMapa.setVisible(false);
        vistaVerMapa.setVisible(true);
        vistaVerMapa.mostrarlo();
    }//GEN-LAST:event_verButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton modificarButton;
    private javax.swing.JButton nuevoButton;
    private javax.swing.JPanel opcionesMapaDefault;
    private javax.swing.JButton verButton;
    private Presentacio.VistaGuardarMapa vistaGuardarMapa;
    private Presentacio.VistaMapaNuevo vistaMapaNuevo;
    private Presentacio.VistaModificarMapa vistaModificarMapa;
    private Presentacio.VistaVerMapa vistaVerMapa;
    // End of variables declaration//GEN-END:variables

    void cierraCrearMapaAbreVistaMapa() {
        vistaMapaNuevo.escondeNuevoMapa();
        vistaMapaNuevo.setVisible(false);
        vistaVerMapa.setVisible(true);
        vistaVerMapa.mostrarlo();
    }
}
