package Presentacio;

/**
 * @autor Joan
 * @dataCreación 19/11/2014
 * @dataÚltimaModificación 19/11/2014
 */
public class VistaMapaNuevo extends javax.swing.JPanel {

    private CtrlPresentacio cPres;

    /**
     * Creates new form VistaMapaNuevo
     */
    public VistaMapaNuevo() {
        initComponents();
    }
    
    /**
     * Creates new form VistaMapaNuevo
     */
    public VistaMapaNuevo(CtrlPresentacio cpres) {
        this.cPres = cpres;
        initComponents();
        vistaMapaIntroducirParams.setVisible(false);
        vistaImportarMapaFichero.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        definirButton = new javax.swing.JButton();
        importarButton = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        nuevoMapaDefault = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vistaMapaIntroducirParams = new Presentacio.VistaMapaIntroducirParams(this.cPres);
        vistaImportarMapaFichero = new Presentacio.VistaImportarMapaFichero(this.cPres);

        definirButton.setText("Definir Parámetros");
        definirButton.setMaximumSize(new java.awt.Dimension(157, 29));
        definirButton.setMinimumSize(new java.awt.Dimension(157, 29));
        definirButton.setPreferredSize(new java.awt.Dimension(157, 29));
        definirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                definirButtonActionPerformed(evt);
            }
        });

        importarButton.setText("Importar Fichero");
        importarButton.setMaximumSize(new java.awt.Dimension(157, 29));
        importarButton.setMinimumSize(new java.awt.Dimension(157, 29));
        importarButton.setPreferredSize(new java.awt.Dimension(157, 29));
        importarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarButtonActionPerformed(evt);
            }
        });

        container.setLayout(new javax.swing.OverlayLayout(container));

        jLabel1.setText("Vamos a crear un nuevo mapa");

        javax.swing.GroupLayout nuevoMapaDefaultLayout = new javax.swing.GroupLayout(nuevoMapaDefault);
        nuevoMapaDefault.setLayout(nuevoMapaDefaultLayout);
        nuevoMapaDefaultLayout.setHorizontalGroup(
            nuevoMapaDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoMapaDefaultLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        nuevoMapaDefaultLayout.setVerticalGroup(
            nuevoMapaDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoMapaDefaultLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel1)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        container.add(nuevoMapaDefault);
        container.add(vistaMapaIntroducirParams);
        container.add(vistaImportarMapaFichero);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(importarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(definirButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(definirButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(importarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void definirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_definirButtonActionPerformed
        nuevoMapaDefault.setVisible(false);
        vistaMapaIntroducirParams.setVisible(true);
        vistaImportarMapaFichero.setVisible(false);
        vistaMapaIntroducirParams.initVisibles();
    }//GEN-LAST:event_definirButtonActionPerformed

    private void importarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarButtonActionPerformed
        nuevoMapaDefault.setVisible(false);
        vistaMapaIntroducirParams.setVisible(false);
        vistaImportarMapaFichero.setVisible(true);
    }//GEN-LAST:event_importarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JButton definirButton;
    private javax.swing.JButton importarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel nuevoMapaDefault;
    private Presentacio.VistaImportarMapaFichero vistaImportarMapaFichero;
    private Presentacio.VistaMapaIntroducirParams vistaMapaIntroducirParams;
    // End of variables declaration//GEN-END:variables

    void escondeNuevoMapa() {
        nuevoMapaDefault.setVisible(true);
        vistaMapaIntroducirParams.setVisible(false);
        vistaImportarMapaFichero.setVisible(false);
    }
}
