package Presentacio;

import javax.swing.JOptionPane;

/**
 * @autor Laura
 * @dataCreación 7/12/2014
 * @dataÚltimaModificación 9/12/2014
 */
public class VistaModificarMapa extends javax.swing.JPanel {

    private CtrlPresentacio cPres;

    /**
     * Creates new form VistaMapaNuevo
     */
    public VistaModificarMapa() {
        initComponents();
    }

    /**
     * Creates new form VistaMapaNuevo
     */
    public VistaModificarMapa(CtrlPresentacio cpres) {
        this.cPres = cpres;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        labelPueblo = new javax.swing.JLabel();
        labelTramo = new javax.swing.JLabel();
        idPuebloLabel = new javax.swing.JLabel();
        idPuebloField = new javax.swing.JTextField();
        nombrePuebloLabel = new javax.swing.JLabel();
        nombrePuebloField = new javax.swing.JTextField();
        idTramoField = new javax.swing.JTextField();
        nombreTramoField = new javax.swing.JTextField();
        idTramoLabel = new javax.swing.JLabel();
        nombreTramoLabel = new javax.swing.JLabel();
        tiempoTramoField = new javax.swing.JTextField();
        kilometrosTramoField = new javax.swing.JTextField();
        costeBilleteTramoField = new javax.swing.JTextField();
        tiempoTramoLabel = new javax.swing.JLabel();
        kilometrosTramoLabel = new javax.swing.JLabel();
        costeBilleteTramoLabel = new javax.swing.JLabel();
        actualizarPueblo = new javax.swing.JButton();
        actualizarTramo = new javax.swing.JButton();

        titulo.setText("Modificar el mapa del sistema");

        labelPueblo.setText("Modificar Pueblo");

        labelTramo.setText("Modificar Tramo");

        idPuebloLabel.setText("ID:");

        idPuebloField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPuebloFieldActionPerformed(evt);
            }
        });

        nombrePuebloLabel.setText("Nombre:");

        idTramoLabel.setText("ID:");

        nombreTramoLabel.setText("Nombre:");

        tiempoTramoLabel.setText("Tiempo:");

        kilometrosTramoLabel.setText("Distancia:");

        costeBilleteTramoLabel.setText("Coste del billete:");

        actualizarPueblo.setText("Actualizar Pueblo");
        actualizarPueblo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPuebloActionPerformed(evt);
            }
        });

        actualizarTramo.setText("Actualizar Tramo");
        actualizarTramo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTramoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addComponent(labelPueblo)
                    .addComponent(labelTramo)
                    .addComponent(actualizarPueblo)
                    .addComponent(actualizarTramo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTramoField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTramoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTramoField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreTramoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tiempoTramoField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tiempoTramoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kilometrosTramoField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kilometrosTramoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(costeBilleteTramoLabel)
                            .addComponent(costeBilleteTramoField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idPuebloField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombrePuebloLabel)
                            .addComponent(nombrePuebloField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(idPuebloLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(47, 47, 47)
                .addComponent(labelPueblo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPuebloLabel)
                    .addComponent(nombrePuebloLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePuebloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPuebloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(actualizarPueblo)
                .addGap(66, 66, 66)
                .addComponent(labelTramo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costeBilleteTramoLabel)
                    .addComponent(kilometrosTramoLabel)
                    .addComponent(tiempoTramoLabel)
                    .addComponent(nombreTramoLabel)
                    .addComponent(idTramoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTramoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTramoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempoTramoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kilometrosTramoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costeBilleteTramoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(actualizarTramo)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idPuebloFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPuebloFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPuebloFieldActionPerformed

    private void actualizarPuebloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarPuebloActionPerformed
        if (this.cPres.hayMapaCargado()) {
            if (!idPuebloField.getText().equals("") && !nombrePuebloField.getText().equals("")) {
                int numPueblos = this.cPres.getNumPueblos();
                boolean idValido = (isNumeric(idPuebloField.getText()) && Integer.parseInt(idPuebloField.getText()) >= 0 && Integer.parseInt(idPuebloField.getText()) < numPueblos);
                if (idValido) {
                    this.cPres.modificarPueblo(idPuebloField.getText(), nombrePuebloField.getText());
                    JOptionPane.showMessageDialog(null, "Se ha modificado el pueblo correctamente");
                    idPuebloField.setText("");
                    nombrePuebloField.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "El ID de pueblo que has introducido no es válido");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor, rellena todos los campos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay ningún mapa cargado en el sistema");
        }
    }//GEN-LAST:event_actualizarPuebloActionPerformed

    private void actualizarTramoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTramoActionPerformed
        if (this.cPres.hayMapaCargado()) {
            if (!idTramoField.getText().equals("") && !nombreTramoField.getText().equals("") && isNumeric(tiempoTramoField.getText()) && isNumeric(kilometrosTramoField.getText()) && isNumeric(costeBilleteTramoField.getText()) && Integer.parseInt(tiempoTramoField.getText()) > 0 && Integer.parseInt(kilometrosTramoField.getText()) > 0 && Integer.parseInt(costeBilleteTramoField.getText()) > 0) {
                int numTramos = this.cPres.getNumTramos();
                boolean idValido = (isNumeric(idTramoField.getText()) && Integer.parseInt(idTramoField.getText()) >= 0 && Integer.parseInt(idTramoField.getText()) < numTramos);
                if (idValido) {
                    this.cPres.modificarTramo(idTramoField.getText(), nombreTramoField.getText(), tiempoTramoField.getText(), kilometrosTramoField.getText(), costeBilleteTramoField.getText());
                    JOptionPane.showMessageDialog(null, "Se ha modificado el tramo correctamente");
                    idTramoField.setText("");
                    nombreTramoField.setText("");
                    tiempoTramoField.setText("");
                    kilometrosTramoField.setText("");
                    costeBilleteTramoField.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "El ID de tramo que has introducido no es válido");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor, rellena todos los campos con un valor correcto");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay ningún mapa cargado en el sistema");
        }
    }//GEN-LAST:event_actualizarTramoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarPueblo;
    private javax.swing.JButton actualizarTramo;
    private javax.swing.JTextField costeBilleteTramoField;
    private javax.swing.JLabel costeBilleteTramoLabel;
    private javax.swing.JTextField idPuebloField;
    private javax.swing.JLabel idPuebloLabel;
    private javax.swing.JTextField idTramoField;
    private javax.swing.JLabel idTramoLabel;
    private javax.swing.JTextField kilometrosTramoField;
    private javax.swing.JLabel kilometrosTramoLabel;
    private javax.swing.JLabel labelPueblo;
    private javax.swing.JLabel labelTramo;
    private javax.swing.JTextField nombrePuebloField;
    private javax.swing.JLabel nombrePuebloLabel;
    private javax.swing.JTextField nombreTramoField;
    private javax.swing.JLabel nombreTramoLabel;
    private javax.swing.JTextField tiempoTramoField;
    private javax.swing.JLabel tiempoTramoLabel;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    private boolean isNumeric(String str) {
        return (str.matches("[+-]?\\d*(\\.\\d+)?") && str.equals("") == false);
    }
}
